CREATE TABLE IF NOT EXISTS users (
    id       BIGSERIAL    PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    email    VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    country  VARCHAR(100) NOT NULL,
    role     VARCHAR(10)  NOT NULL DEFAULT 'USER'
);
